Fix to define alias :remove before definition
rspec tests fail because eager loading is not turned on by default 
undefined method `remove' for module `Mongoid::Paranoia' (NameError)